version: '3.8'

services:
  mysql:
    container_name: 'guide-mysql'
    image: 'mysql:latest'
    environment:
      - MYSQL_DATABASE=imdb
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=admin
    ports:
      - '3306:3306'
    command: --init-file /init.sql
    volumes:
        - ./src/main/resources/db/init/init.sql:/init.sql

  app:
    image: openjdk:21-jdk-slim
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: ["./mvnw", "spring-boot:run"]
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/imdb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - mysql